### ISSUE TITLE
Version 2.8.1 - master.dacpac reference is not found

### ISSUE THREAD

**Issue by rapolas-oag** [jmezach/MSBuild.Sdk.SqlProj#615] opened 2024-08-30 10:18 UTC
Version: 2.8.1
Deployment on Docker image mcr.microsoft.com/mssql/server:2019-latest
Sqlpackage version tested with 150.* and the latest 162.3.566.1

sqlpackage returns error:

```
Initializing deployment (Start) 2024-08-30 12:41:29 *** No file was supplied for reference master.dacpac; deployment might fail. When package was created, the original referenced file was located C:\Users\username\.nuget\packages\microsoft.sqlserver.dacpacs.master\150.1.1/tools/master.dacpac. 2024-08-30 12:41:29 Initializing deployment (Failed)
```

Notes:
* master.dacpac is in the same directory as dacpac of database I want to deploy;
* master is referenced:
```xml
<Project Sdk="MSBuild.Sdk.SqlProj/2.8.1">
     ...
    <ItemGroup>
        <PackageReference Include="Microsoft.SqlServer.Dacpacs.Master" DacpacName="master" DatabaseVariableLiteralValue="master" Version="150.1.1" />
    </ItemGroup>
</Project>
```
* issue gone once ```<Project Sdk="MSBuild.Sdk.SqlProj/2.8.1">``` was changed to ```<Project Sdk="MSBuild.Sdk.SqlProj/2.7.2">```

**Comment by ErikEJ** [comment] 2024-08-30 15:12
How about 2.8.0 ?

**Comment by rapolas-oag** [comment] 2024-09-02 08:59
@ErikEJ After changing version from 2.7.2 to 2.8.0, deployment which was working as expected in Docker started to fail again.

Error: 
```
2024-09-02 11:56:31 Initializing deployment (Start)
2024-09-02 11:56:31 2024-09-02 08:56:31.53 spid53      Attempting to load library 'xplog70.dll' into memory. This is an informational message only. No user action is required.
2024-09-02 08:56:31.55 spid53      Using 'xplog70.dll' version '2019.150.4355' to execute extended stored procedure 'xp_msver'. This is an informational message only; no user action is required.
2024-09-02 08:56:31.73 spid53      Attempting to load library 'xpstar.dll' into memory. This is an informational message only. No user action is required.
2024-09-02 08:56:31.75 spid53      Using 'xpstar.dll' version '2019.150.4355' to execute extended stored procedure 'xp_instance_regread'. This is an informational message only; no user action is required.
*** No file was supplied for reference master.dacpac; deployment might fail. When package was created, the original referenced file was located C:\Users\user\.nuget\packages\microsoft.sqlserver.dacpacs.master\150.1.1/tools/master.dacpac.
2024-09-02 11:56:34 Initializing deployment (Failed)
2024-09-02 11:56:35 *** An error occurred during deployment plan generation. Deployment cannot continue.
2024-09-02 11:56:35 Error SQL0: The reference to external elements from the source named 'master.dacpac' could not be resolved, because no such source is loaded.
```

**Comment by ErikEJ** [comment] 2024-09-17 05:37
I think we need a simple repro project that reproduces the issue in order to help

**Comment by ErikEJ** [comment] 2024-09-22 08:06
@rapolas-oag Ping? Can you provide a simple repro?

**Comment by rapolas-oag** [comment] 2024-09-23 07:12
@ErikEJ I will try to provide example by the end of this week.

**Comment by rapolas-oag** [comment] 2024-09-27 12:27
I compared dacpacs created with different versions.

Differences in model.xml:
* version 2.7.2
```xml
<?xml version="1.0" encoding="utf-8"?>
<DataSchemaModel FileFormatVersion="1.2" SchemaVersion="2.4" DspName="Microsoft.Data.Tools.Schema.Sql.Sql150DatabaseSchemaProvider" CollationLcid="1033" CollationCaseSensitive="False" xmlns="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02">
	<Header>
		<CustomData Category="Reference" Type="SqlSchema">
			<Metadata Name="FileName" Value="master.dacpac" />
			<Metadata Name="LogicalName" Value="master.dacpac" />
			<Metadata Name="SuppressMissingDependenciesErrors" Value="False" />
			<Metadata Name="ExternalParts" Value="[master]" />
		</CustomData>
	</Header>
	<Model>
...
```
* version 2.8.1
```xml
<?xml version="1.0" encoding="utf-8"?>
<DataSchemaModel FileFormatVersion="1.2" SchemaVersion="2.4" DspName="Microsoft.Data.Tools.Schema.Sql.Sql150DatabaseSchemaProvider" CollationLcid="1033" CollationCaseSensitive="False" xmlns="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02">
	<Header>
		<CustomData Category="Reference" Type="SqlSchema">
			<Metadata Name="FileName" Value="C:\Users\username\.nuget\packages\microsoft.sqlserver.dacpacs.master\150.1.1/tools/master.dacpac" />
			<Metadata Name="LogicalName" Value="master.dacpac" />
			<Metadata Name="SuppressMissingDependenciesErrors" Value="False" />
			<Metadata Name="ExternalParts" Value="[master]" />
		</CustomData>
	</Header>
...
```

Seems that the problem is happening on this line: ```<Metadata Name="FileName" Value="C:\Users\username\.nuget\packages\microsoft.sqlserver.dacpacs.master\150.1.1/tools/master.dacpac" />```

**Comment by ErikEJ** [comment] 2024-09-27 13:16
@rapolas-oag I believe this has been fixed in the latest DacFX (162.4.92) which will be included in our next release (2.9.0)

@jmezach FYI!

**Comment by rapolas-oag** [comment] 2024-09-27 13:22
[like]  Rapolas Dangveckas reacted to your message:
________________________________

**Comment by ErikEJ** [comment] 2024-09-28 17:00
Looks like a duplicate of #550

**Comment by rapolas-oag** [comment] 2024-10-01 06:49
@ErikEJ are there any timeline when v 2.9.0 will be released?

And I am happy to close this as duplicate

**Comment by ErikEJ** [comment] 2024-10-01 07:36
@rapolas-oag Quite soon, I think /cc @jmezach

**Comment by ErikEJ** [comment] 2024-10-01 13:46
@rapolas-oag 2.9.0 is out now, looking forward to your findings

**Comment by rapolas-oag** [comment] 2024-10-02 07:47
I tried with latest version and still get same error, checked Origin.xml:
```xml
  <Operation>
    <Identity>95451547-e95e-4a9b-8372-31d7d868f95e</Identity>
    <Start>2024-10-02T10:42:41.9001966+03:00</Start>
    <End>2024-10-02T10:42:41.9013384+03:00</End>
    <ProductName>Microsoft.SqlServer.Dac.Extensions, Version=162.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</ProductName>
    <ProductVersion>162.4.92.3</ProductVersion>
    <ProductSchema>http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02</ProductSchema>
  </Operation>
```
I assume this is the latest as DACPAC is 162.4.92+ version.

And model.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<DataSchemaModel FileFormatVersion="1.2" SchemaVersion="2.4" DspName="Microsoft.Data.Tools.Schema.Sql.Sql150DatabaseSchemaProvider" CollationLcid="1033" CollationCaseSensitive="False" xmlns="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02">
	<Header>
		<CustomData Category="Reference" Type="SqlSchema">
			<Metadata Name="FileName" Value="C:\Users\username\.nuget\packages\microsoft.sqlserver.dacpacs.master\150.1.1/tools/master.dacpac" />
			<Metadata Name="LogicalName" Value="master.dacpac" />
			<Metadata Name="SuppressMissingDependenciesErrors" Value="False" />
			<Metadata Name="ExternalParts" Value="[master]" />
		</CustomData>
	</Header>
...
```

**Comment by ErikEJ** [comment] 2024-10-03 08:59
Have you tried building your .dacpac on a Linux box? (Looks like you are building on Windows and deploying on Linux just now)

**Comment by ErikEJ** [comment] 2024-10-03 09:08
Just tested with the Microsoft.Build.Sql SDK, and this results in the same behavior.

I suggest you report a bug here: https://github.com/microsoft/DacFx

I will investigate if we can work around it.

**Comment by ErikEJ** [comment] 2024-10-03 09:24
@jmezach Wonder if we should consider changing this?

```csharp
        public static void AddReference(this TSqlModel model, string referencePath, string externalParts, bool suppressErrorsForMissingDependencies)
        {
            ArgumentNullException.ThrowIfNull(model);

            var dataSchemaModel = GetDataSchemaModel(model);

            var customData = Activator.CreateInstance(Type.GetType("Microsoft.Data.Tools.Schema.SchemaModel.CustomSchemaData, Microsoft.Data.Tools.Schema.Sql"), "Reference", "SqlSchema");
            var setMetadataMethod = customData.GetType().GetMethod("SetMetadata", BindingFlags.Public | BindingFlags.Instance);
            setMetadataMethod.Invoke(customData, new object[] { "FileName", referencePath });
            setMetadataMethod.Invoke(customData, new object[] { "LogicalName", Path.GetFileName(referencePath) });

```

**Comment by jmezach** [comment] 2024-10-03 09:44
Changing it to what?

**Comment by ErikEJ** [comment] 2024-10-03 09:59
` setMetadataMethod.Invoke(customData, new object[] { "FileName", Path.GetFileName(referencePath) });`

**Comment by jmezach** [comment] 2024-10-03 10:21
As in stripping the path out of it so that is just the name of the `.dacpac` file? That would require us to copy the reference so that it is next to the output `.dacpac`, which I believe we do but we might want to double check that. Kind of interesting though that it worked before?

**Comment by ErikEJ** [comment] 2024-10-03 10:40
I think DacFX stripped the path previously before writing the property, but stopped doing that for some reason ( as you can see from the samples above)

**Comment by jmezach** [comment] 2024-10-04 09:39
Perhaps we should make this change and ship a preview version so that @rapolas-oag can test it to verify it works for their scenario?

**Comment by ErikEJ** [comment] 2024-10-04 09:42
@jmezach Yes, I think that could be helpful, and @rapolas-oag seems to be available to verify.

I will do a PR!

**Comment by ErikEJ** [comment] 2024-10-04 10:01
Yikes - making that change causes this failure:

```
Test method MSBuild.Sdk.SqlProj.DacpacTool.Tests.PackageBuilderTest.AddReference_FileExists threw exception: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.Data.Tools.Schema.SchemaModel.DataSchemaModelException: Failed to load tmpB790.dacpac. ---> Microsoft.Data.Tools.Schema.Sql.Build.SqlPackageException: Could not find file 'C:\Code\Github\MSBuild.Sdk.SqlProj\test\DacpacTool.Tests\bin\Debug\net6.0\tmpB790.dacpac'. ---> System.IO.FileNotFoundException: Could not find file 'C:\Code\Github\MSBuild.Sdk.SqlProj\test\DacpacTool.Tests\bin\Debug\net6.0\tmpB790.dacpac'.

```

**Comment by jmezach** [comment] 2024-10-04 10:42
I guess that makes sense, as it will need to load the actual `.dacpac` file from somewhere but it is not in the same folder as where the `DacpacTool` is running probably.

**Comment by jmezach** [comment] 2024-10-04 15:30
I just checked out our 2.7 release branch and ran a build of one of our test projects that has a PackageReference and checked the `model.xml`. This already includes the full path to the `.dacpac` file in my local NuGet cache, so I'm a bit confused as to what has changed between 2.7.2 and 2.8.0.

**Comment by ErikEJ** [comment] 2024-10-04 19:22
Thid sounds more and more like a DacFX cross platform issue.

@rapolas-oag Are you using the latest sqlpackage version during deployment?

162.4.92

**Comment by ErikEJ** [comment] 2024-10-05 15:14
@jmezach Wonder if it is the broken path seperators?

`C:\Users\username\.nuget\packages\microsoft.sqlserver.dacpacs.master\150.1.1/tools/master.dacpac`

**Comment by jmezach** [comment] 2024-10-07 13:17
Could be, although this hasn't really changed between 2.7.2 and 2.8.0 either.

@rapolas-oag Would be interested to know if building the `.dacpac` on Linux changes anything here.

**Comment by rapolas-oag** [comment] 2024-10-07 17:31
Issue was reported when:
* build on Win using dotnet CLI;
* deploy to Docker Linux

Now, ran build on Azure build agent:
```
Agent name: 'Hosted Agent'
Current agent version: '3.245.0'
Operating System
Ubuntu
22.04.5
LTS
Runner Image
Image: ubuntu-22.04
Version: 20240922.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240922.1/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240922.1
```

And got this model.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<DataSchemaModel FileFormatVersion="1.2" SchemaVersion="2.4" DspName="Microsoft.Data.Tools.Schema.Sql.Sql150DatabaseSchemaProvider" CollationLcid="1033" CollationCaseSensitive="False" xmlns="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02">
	<Header>
		<CustomData Category="Reference" Type="SqlSchema">
			<Metadata Name="FileName" Value="/home/vsts/.nuget/packages/microsoft.sqlserver.dacpacs.master/150.1.1/tools/master.dacpac" />
			<Metadata Name="LogicalName" Value="master.dacpac" />
			<Metadata Name="SuppressMissingDependenciesErrors" Value="False" />
			<Metadata Name="ExternalParts" Value="[master]" />
		</CustomData>
	</Header>
```

Origin.xml
```xml
  <Operation>
    <Identity>5b0ec4f4-747b-47c1-a7be-85f901880bd5</Identity>
    <Start>2024-10-07T17:24:54.9124836+00:00</Start>
    <End>2024-10-07T17:24:54.9138120+00:00</End>
    <ProductName>Microsoft.SqlServer.Dac.Extensions, Version=162.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</ProductName>
    <ProductVersion>162.4.92.3</ProductVersion>
    <ProductSchema>http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02</ProductSchema>
  </Operation>
```

Seems that Linux build has same issue as well.

**Comment by ErikEJ** [comment] 2024-10-07 17:46
@rapolas-oag Have you tried publishing this package??

**Comment by rapolas-oag** [comment] 2024-10-08 07:13
Took same dackpac which was build on Linux agent and tried to deploy on Docker SQL Server instance (Ubuntu based ```mcr.microsoft.com/mssql/server:2019-latest``` image) and it was ok.

When building project on Windows:
* fails to deploy on Docker Linux;
* succeed deploy on Windows server;

When building project on Linux (Azure DevOps agent):
* succeeds deploy on Docker Linux;
* succeeds deploy on Windows server;

**Comment by ErikEJ** [comment] 2024-10-08 07:42
Given the 75% success rate 😆 , I think we can probably close this? @jmezach

**Comment by ErikEJ** [comment] 2024-10-08 07:43
@jmezach Still wonder if it the "broken" path, that occurs on Windows only?

**Comment by ErikEJ** [comment] 2024-10-08 08:14
`<DacpacFile>%(_ResolvedPackageReference.PhysicalLocation)/tools/%(PackageReference.Identity).dacpac</DacpacFile>`

@jmezach We could try to normalize to all "/" in reference paths? (In Dacpac tool)

**Comment by jmezach** [comment] 2024-10-08 08:30
It is worth a try I guess

**Comment by jmezach** [comment] 2024-10-08 11:09
@rapolas-oag We've just published a preview version (2.10.0-beta.6.g87ee574993) up on NuGet.org that normalizes the paths to be all forward slashes. Could you try the test you've described in https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/issues/615#issuecomment-2399030319 again with this version to see if that makes a difference?

**Comment by rapolas-oag** [comment] 2024-10-08 14:38
@jmezach it is working when building on Windows and deploying on Linux (Docker).
Thank you

**Comment by jmezach** [comment] 2024-10-08 14:41
@ErikEJ I guess we can merge #638?

**Comment by ErikEJ** [comment] 2024-10-08 15:23
@jmezach Hurray, let's do that !

**Closed as completed** 2024-10-09 07:26 UTC

**Comment by jmezach** [comment] 2024-10-09 07:57
Version 2.9.1 is up on NuGet.org now which includes a fix for this.
